collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.04887218
color:
  saturation: 0.5451128
  brandStrength: 0.9199785
  lightness: 0.2400644
  brandColors:
    - '#FDFDFD'
    - '#151F1F'
    - '#9299A3'
    - '#6F7788'
    - '#91775C'
  rhythmicContrast: 0.2701396
layout_spectrum: 0.9124597
name: CrazyKangaroo
