collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.04887218
color:
  saturation: 0.6718582
  brandStrength: 0.9199785
  rhythmicContrast: 0.3990332
  brandColors:
    - '#FDFDFD'
    - '#151F1F'
    - '#9299A3'
    - '#6F7788'
    - '#91775C'
  lightness: 0.04027925
layout_spectrum: 0.9446831
name: CrazyKangaroo
